services:
  - type: web
    name: erudite-frontend
    runtime: docker
    plan: standard
    region: oregon
    dockerfile: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: VITE_API_URL
        value: https://erudite-api.onrender.com/api

  - type: web
    name: erudite-api
    runtime: docker
    plan: standard
    region: oregon
    dockerfile: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://erudite-frontend.onrender.com
      - key: SESSION_DRIVER
        value: cookie
    maxInstanceCount: 3
    healthCheckPath: /api/health
